---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
data:
  config.json: |
    {
      "server": true,
      "client_addr": "0.0.0.0",
      "ui": true,
      "bind_addr": "0.0.0.0",
      "raft_protocol": 3,
      "retry_join": [ "provider=k8s label_selector=\"app=consul,role=server\" namespace=\"vault\"" ],
      "ca_file": "/etc/tls/ca.pem",
      "cert_file": "/etc/tls/consul.pem",
      "data_dir": "/consul/data",
      "datacenter": "vault",
      "key_file": "/etc/tls/consul-key.pem",
      "verify_incoming": true,
      "verify_outgoing": true
    }