---
apiVersion: v1
kind: Service
metadata:
  name: consul-ui
spec:
  type: ClusterIP
  ports:
    - name: ui
      port: 80
      targetPort: 8500
      protocol: TCP
  selector:
    app: consul
    role: server

---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
    - name: rpc
      port: 8300
    - name: lan
      port: 8301
    - name: wan
      port: 8302
    - name: api
      port: 8500
      protocol: TCP
    - name: dns-udp
      port: 8600
      protocol: UDP
    - name: dns-tcp
      port: 8600
      protocol: TCP
  clusterIP: None
  selector:
    app: consul
    role: server